### ISSUE TITLE
[SONiC]- gnmi/telemetry -- Facing issue while performing the SET & SUBSCRIBE with pygnmi.

### ISSUE THREAD

**Issue by donbharath21** [sonic-net/sonic-gnmi#150]
Hi all,

When iam try to run the SET & SUBSCRIBE script getting an error. But for the CAPABILITIES & GET operation i didn't seeing any issue. "For this iam using the latest communtiy (Master branch - sonic broadcom image)".

Capabilities.py 
```
# Modules
from pygnmi.client import gNMIclient
import json

# Variables
host = {
    "ip_address": "50.0.0.20",
    "port": 50051,
    "username": "admin",
    "password": "YourPaSsWoRd",
}

# Body
if __name__ == "__main__":
    with gNMIclient(
        target=(host["ip_address"], host["port"]),
        username=host["username"],
        password=host["password"],
        path_root="/etc/sonic/telemetry/certs/ca.pem",
        path_cert="/etc/sonic/telemetry/certs/server.pem",
        path_key="/etc/sonic/telemetry/certs/server.key",
        override="sonic",
        #override="dev-pygnmi-sonic-003",
    ) as gc:
        result = gc.capabilities()
        print(json.dumps(result, indent=4))


```
output of the capabilities:
{
    "supported_models": [
        {
            "name": "openconfig-acl",
            "organization": "OpenConfig working group",
            "version": "1.0.2"
        },
        {
            "name": "openconfig-acl",
            "organization": "OpenConfig working group",
            "version": ""
        },
        {
            "name": "openconfig-interfaces",
            "organization": "OpenConfig working group",
            "version": "1.0.2"
        },
        {
            "name": "openconfig-lldp",
            "organization": "OpenConfig working group",
            "version": "1.0.2"
        },
        {
            "name": "openconfig-platform",
            "organization": "OpenConfig working group",
            "version": "1.0.2"
        },
        {
            "name": "openconfig-system",
            "organization": "OpenConfig working group",
            "version": "1.0.2"
        },
        {
            "name": "ietf-yang-library",
            "organization": "IETF NETCONF (Network Configuration) Working Group",
            "version": "2016-06-21"
        },
        {
            "name": "sonic-db",
            "organization": "SONiC",
            "version": "0.1.0"
        }
    ],
    "supported_encodings": [
        "json",
        "json_ietf"
    ],
    "gnmi_version": "0.7.0"
}

GET operation script:
Get.py --> Here iam getting the "openconfig-acl:acl"

```
# Modules
from pygnmi.client import gNMIclient
import json

# Variables
host = {
    "ip_address": "50.0.0.20",
    "port": 50051,
    "username": "admin",
    "password": "YourPaSsWoRd",
}


# Body
if __name__ == "__main__":

     # paths = ['openconfig-interfaces:interfaces/interface[name=Ethernet0]']
     paths = ['/openconfig-acl:acl']
     #paths = ['/openconfig-interfaces:interfaces']
     #paths = ['/openconfig-lldp:lldp']
     #paths = ['/openconfig-platform:components']
     #paths = ['/ietf-yang-library:modules-state']

     with gNMIclient(
        target=(host["ip_address"], host["port"]),
        username=host["username"],
        password=host["password"],
        path_root="/home/sonic/bharath/certs/ca.pem",
        path_cert="/home/sonic/bharath/certs/server.pem",
        path_key="/home/sonic/bharath/certs/server.key",
        override="sonic",
    ) as gc:
        result = gc.get(path=paths, encoding='json')
        print(json.dumps(result, indent=4))
```
output of GET:
{
    "notification": [
        {
            "timestamp": 1688309679309160550,
            "prefix": null,
            "alias": null,
            "atomic": false,
            "update": [
                {
                    "path": "openconfig-acl:acl",
                    "val": {}
                }
            ]
        }
    ]
}

subscribe.py
```
#!/usr/bin/env python

# Modules
import json  # Added missing import statement
from pygnmi.client import gNMIclient, telemetryParser

# Variables
host = {
    "ip_address": "50.0.0.20",
    "port": 50051,
    "username": "admin",
    "password": "YourPaSsWoRd",
}

subscribe = {
    'subscription': [
        {
            'path': 'openconfig-interfaces:interfaces/interface[name=Ethernet0]',
            #path: ['openconfig-interfaces:interfaces/interface[name=Ethernet0]'],
            #'path' : 'openconfig-acl:acl',
            #'path' : 'openconfig-interfaces:interfaces',
            #'path' : 'openconfig-lldp:lldp',
            #'path' : 'openconfig-platform:components',
            #'path' : 'ietf-yang-library:modules-state',
            'mode': 'sample',
            'sample_interval': 10000000000
        }
    ],
    #'use_aliases': False,
    'mode': 'stream',
    'encoding': 'proto'
}

# Body
if __name__ == "__main__":
    with gNMIclient(
            target=(host["ip_address"], host["port"]),
            username=host["username"],
            password=host["password"],
            path_root="/etc/sonic/telemetry/certs/ca.pem",
            path_cert="/etc/sonic/telemetry/certs/server.pem",
            path_key="/etc/sonic/telemetry/certs/server.key",
            #path_root="/home/sonic/bharath/certs/ca.pem",
            #path_cert="/home/sonic/bharath/certs/server.pem",
            #path_key="/home/sonic/bharath/certs/server.key",
            override="sonic",
    ) as gc:
        telemetry_stream = gc.subscribe(subscribe=subscribe)
       
       for parsed_data in telemetry_stream:
            print(json.dumps(parsed_data, indent=4))

```
output:
Traceback (most recent call last):
  File "subscribe-test.py", line 50, in <module>
    for parsed_data in telemetry_stream:
  File "/usr/local/lib/python3.6/dist-packages/grpc/_channel.py", line 426, in __next__
    return self._next()
  File "/usr/local/lib/python3.6/dist-packages/grpc/_channel.py", line 826, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.UNIMPLEMENTED
        details = "Empty target data not supported yet"
        debug_error_string = "UNKNOWN:Error received from peer ipv4:50.0.0.20:50051 {created_time:"2023-09-13T15:12:21.086493292+05:30", grpc_status:12, grpc_message:"Empty target data not supported yet"}"
>

Same error facing for the SET aswell. Is the SET & SUBSCRIBE have the support in the image?

**Comment by sneelam20** [comment]
Hello,

Since this is an old issue, can you try this again and let us know if this is still an issue?

**Comment by sneelam20** [comment]
Closing this as obsolete. Please reopen if necessary.
