### ISSUE TITLE
Updated installation instructions?

### ISSUE THREAD

**Issue by lamoni** [sonic-net/sonic-gnmi#18]
I'm trying to install following the directions in the README but get this message:
```
go get github.com/Azure/sonic-telemetry/telemetry: no matching versions for query "upgrade"
```
Is there a different process I should be following?

**Comment by sneelam20** [comment]
"go get" will no longer work. Please build sonic using the instructions at https://github.com/sonic-net/sonic-buildimage/blob/master/README.md
