### ISSUE TITLE
support for Red hat Linux 

### ISSUE THREAD

**Issue by nagranjeet** [sonic-net/sonic-gnmi#21]
Hi,
How to compile this on Red Hat Enterprise Linux Server. 

Also am able to run dialout_server_cli but its listening on localhost but i could not see any option to run an any specific IP.dialout_server_cli -help
Usage of dialout_server_cli:
  -allow_no_client_auth
        When set, telemetry server will request but not require a client certificate.
  -alsologtostderr
        log to standard error as well as files
  -ca_crt string
        CA certificate for client certificate validation. Optional.
  -insecure
        Skip providing TLS cert and key, for testing only!
  -log_backtrace_at value
        when logging hits line file:N, emit a stack trace
  -log_dir string
        If non-empty, write log files in this directory
  -logtostderr
        log to standard error instead of files
  -port int
        port to listen on (default -1)
  -server_crt string
        TLS server certificate
  -server_key string
        TLS server private key
  -stderrthreshold value
        logs at or above this threshold go to stderr
  -v value
        log level for V logs
  -vmodule value
        comma-separated list of pattern=N settings for file-filtered logging

Is any way to run this binary with specific IP ?

**Comment by sneelam20** [comment]
Is this still relevant?

**Comment by sneelam20** [comment]
Closing issue since there has been any activity since 2021.

**Comment by sneelam20** [comment]
Closing issue since there has been any activity since 2021.

**Comment by sneelam20** [comment]
Closing issue since there has been any activity since 2021.
