### ISSUE TITLE
The dialout client cannot connect to the dialout server using the configured source ip

### ISSUE THREAD

**Issue by rockyrth** [sonic-net/sonic-gnmi#48]
Hi
    Telemetry can config the source ip
             127.0.0.1:6379[4]> HGETALL TELEMETRY_CLIENT|Global
              1) "src_ip"
               2) "1.1.1.1"
    
    But the configured  source ip doest's works,  because the dialout client  connect to the dialout server  by using a random ip of a device.

**Comment by rockyrth** [comment]
I have implemented the code, could anyone take a look

https://github.com/sonic-net/sonic-gnmi/pull/47

**Comment by rockyrth** [comment]
OK, I get the comment, let's add the unit test.

**Comment by sneelam20** [comment]
#47 has been closed. Is this still relevant?

**Comment by sneelam20** [comment]
Closing this as obsolete.
